[0.0.2] Add base code, configuration and tests
instabase/instabase-sdk-py pull request #1
Opened 2022-09-13 05:18 UTC by mohit-chawla

[x] Tested that the SDK works.
[x] Added .gitignore

2022-09-13 16:17 UTC, ashishdahiya requested changes

2022-09-13 16:17 UTC, ashishdahiya commented on README.md
> +2. `IB_ROOT_URL` : Root URL of Instabase instance, eg: `https://apps.instabase.com`
remove https://apps.instabase.com

2022-09-13 16:17 UTC, ashishdahiya commented on README.md
> +```
let's discuss this example over a call

2022-09-13 16:17 UTC, ashishdahiya commented on src/instabase/__version__.py
> +__url__ = "https://apps.instabase.com"
remove __url__ ?

2022-09-13 16:17 UTC, ashishdahiya commented on src/instabase/sdk.py
> +        return urllib.parse.urljoin(self.root_url,'api/')+version+'/solution/run_developers_portal'
rename this API endpoint?

2022-09-13 16:17 UTC, ashishdahiya commented on src/instabase/sdk.py
> +                    'use_flow_batch_mode': True
Review flags

2022-09-13 16:17 UTC, ashishdahiya commented on tests/test_sdk.py
> +file_url = 'https://apps.instabase.com/static/assets/images/cloud-developers/us-bs/sample-us-bs-1.jpeg'
Would like to understand file_url better

2022-09-13 18:09 UTC, mohit-chawla commented on README.md
> +2. `IB_ROOT_URL` : Root URL of Instabase instance, eg: `https://apps.instabase.com`
done

2022-09-13 18:10 UTC, mohit-chawla commented on src/instabase/__version__.py
> +__url__ = "https://apps.instabase.com"
done

2022-09-13 18:10 UTC, mohit-chawla commented on src/instabase/sdk.py
> +        return urllib.parse.urljoin(self.root_url,'api/')+version+'/solution/run_developers_portal'
this is private.

2022-09-13 18:10 UTC, mohit-chawla commented on src/instabase/sdk.py
> +                    'use_flow_batch_mode': True
waiting on @nveenjain's PR to be merged before I do this, else it will break the sdk.

2022-09-13 18:10 UTC, mohit-chawla commented on tests/test_sdk.py
> +file_url = 'https://apps.instabase.com/static/assets/images/cloud-developers/us-bs/sample-us-bs-1.jpeg'
sure, we can discuss on a call.

2022-09-13 22:49 UTC, mohit-chawla commented on src/instabase/sdk.py
> +        return urllib.parse.urljoin(self.root_url,'api/')+version+'/solution/run_developers_portal'
Had a chat with @ashishdahiya 
`https://apps.instabase.com/api/v1/cloud/app/run`

@nveenjain lets update the and cloud nginx, go-sdk to align with this.

2022-09-14 06:59 UTC, nveenjain commented on src/instabase/sdk.py
> +                    'use_flow_batch_mode': True
This is done, these flags can be removed.

2022-09-14 21:55 UTC, mohit-chawla commented on README.md
> +```
as discussed will be address in 0.0.3

2022-09-14 21:55 UTC, mohit-chawla commented on src/instabase/sdk.py
> +        return urllib.parse.urljoin(self.root_url,'api/')+version+'/solution/run_developers_portal'
Will be changed and released in 0.0.3

2022-09-14 21:56 UTC, mohit-chawla commented on src/instabase/sdk.py
> +                    'use_flow_batch_mode': True
Will be changed and released in 0.0.3

2022-09-14 23:42 UTC, ashishdahiya approved these changes

2022-09-14 23:45 UTC, merged

2022-09-19 18:59 UTC, mohit-chawla commented on src/instabase/sdk.py
> +        return urllib.parse.urljoin(self.root_url,'api/')+version+'/solution/run_developers_portal'
Update on this: the `https://apps.instabase.com/api/v1/cloud/app/run` has been changed. For now, we have both for backward compatibility so that the frontend doesnt break. Once we push the updated pypi package 0.0.3 we will remove support for older url format